source "https://rubygems.org"

gem 'sinatra'
gem "rack"
gem 'rake'

gem 'foreman'
gem 'sparks', github: "revans/sparks", branch: "master"

# gem "rack-contrib"
# gem "sinatra-contrib"


group :production do
  gem 'sequel_pg', require: 'sequel'
  gem 'thin'
end

group :development do
  gem "sprockets"

  # styling
  gem "bourbon"
  gem "neat"

  # development tools
  gem "sass"
  gem "coffee-script"
  gem "rack-livereload"

  # auto-compile
  gem "guard-sass"
  gem "guard-coffeescript"
  gem "guard-livereload"

  # compress js
  # gem "uglify"

  gem "rdoc"
end

group :development, :test do
  # gem 'sqlite3'
  gem 'pry'
end

group :test do
  gem 'minitest',   require: false
  gem 'rack-test',  require: false
end
