guard 'sass',         input: 'apps/assets/stylesheets',    output: 'public/stylesheets'
guard 'coffeescript', input: 'apps/assets/coffeescripts',  output: 'public/javascripts'

guard 'livereload' do
  watch("apps/api.rb")
  watch(%r{apps/views/.+\.(erb|haml|slim)})
  watch(%r{apps/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  # watch(%r{config/locales/.+\.yml})
end
